scripts: updated

diff --git a/scripts/migrate b/scripts/migrate
--- a/scripts/migrate
+++ b/scripts/migrate
@@ -18,13 +18,19 @@ for f in migrations/*.sql;
      # execute command with minimal logging
      # -E no echo
      # -q quietly
+
+     # we could pipe to sed to print with indentation: | sed 's/^/ /'
      psql -Eq $DB_URI -f $f;
 
      # TODO: use `$?` to determine the color of the output
-     # i.e. if $? == 1 do echo " 𝘅 ${RED}$f${RESET}";
-
-     echo " ✔ ${GREEN}$f${RESET}";
-     echo ""
-     echo " ---------------------------------------- "
-     echo ""
+     if [ $? != 0 ]; then
+         echo " ${RED} *** Migration Failed *** ${RESET}";
+         echo " 𝘅 ${RED}$f${RESET}";
+         exit $?;
+     else
+         echo " ✔ ${GREEN}$f${RESET}";
+         echo "";
+         echo " ---------------------------------------- ";
+         echo "";
+     fi
 done
